[package]
name = "go-owasm"
version = "0.2.0"
authors = ["Sorawit Suriyakarn <swit@bandprotocol.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
owasm = { git = "https://github.com/bandprotocol/owasm", rev = "8dc6cb7fd7f3a601d43df6934f2ce1a8d3ba062e" }
cosmwasm-vm = { git = "https://github.com/CosmWasm/cosmwasm", rev = "263202f13fef3bfabc2e1036514667812f0e7e62" }
failure = "0.1.6"

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = false
debug-assertions = false
codegen-units = 16
panic = "unwind"
incremental = true
overflow-checks = true
