[package]
name = "go-owasm"
version = "0.2.0"
authors = ["Sorawit Suriyakarn <swit@bandprotocol.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
owasm = { git = "https://github.com/bandprotocol/owasm", rev = "cb30fe93d0b2b745e485ef398bec6cccf7e00d97" }
failure = "0.1.6"

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = false
debug-assertions = false
codegen-units = 16
panic = "unwind"
incremental = true
overflow-checks = true
