[package]
name = "go-owasm"
version = "0.1.0"
authors = ["Sorawit Suriyakarn <swit@bandprotocol.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
owasm = { git = "https://github.com/bandprotocol/owasm", rev = "2c06d1d7b26fe763e939f9866a6316846b932e6d" }
cosmwasm-vm = "0.13.2"
failure = "0.1.6"

[profile.release]
opt-level = 3
debug = false
rpath = true
lto = false
debug-assertions = false
codegen-units = 16
panic = "unwind"
incremental = true
overflow-checks = true
