name: Build shared libraries

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      
jobs:
  push_shared_libraries:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker
        run: |
          make docker-image-linux
          make docker-image-osx

      - name: Build shared libraries
        run: |
          make release-linux
          make release-osx

      - name: Check output
        run: |
          ls -l ./api

      - name: Check if there is any change
        id: check-diff
        run: |
          git diff --quiet || echo "::set-output name=diff::true"

      - name: Config and push new libraries
        if: steps.check-diff.outputs.diff == 'true'
        run: |
          git config --global user.name 'bandbot'
          git config --global user.email 'bandprotocol@users.noreply.github.com'
          git add -A
          git commit -am "Built release libraries"
          git push

  # build_static_lib:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build static library for Alpine
  #       run: make release-build-alpine
  #     - name: Debug build results
  #       run: ls -l ./internal/api
  #     - name: Collect artifacts
  #       run: |
  #         mkdir artifacts
  #         cp ./internal/api/libwasmvm_muslc.x86_64.a artifacts/libwasmvm_muslc.x86_64.a
  #     - name: Create checksums
  #       working-directory: artifacts
  #       run: sha256sum * > checksums.txt && cat checksums.txt
  #     - name: Store artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: artifacts
  #         path: artifacts
